name: flutter_radio_player_example
description: Example app for flutter_radio_player.
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_radio_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  flutter_radio_player_platform_interface:
    path: ../../flutter_radio_player_platform_interface
  flutter_radio_player_android:
    path: ../../flutter_radio_player_android
  flutter_radio_player_ios:
    path: ../../flutter_radio_player_ios

flutter:
  uses-material-design: true
